### ISSUE TITLE
cuxfilter dashboard

### ISSUE THREAD

**Issue by jtpio** [jupytercon/2020-exactlyallan#21]
Similar to #19, but for the cuxfilter dashboard:

![image](https://user-images.githubusercontent.com/591645/94931293-e57b5400-04c7-11eb-9a6e-bfc9010ac14f.png)

At the moment it redirects to http://localhost:8888/proxy/36427, which doesn't work on the hosted notebook server.

Maybe the fix is to use the right `jupyter-server-proxy` config like in #20? 

cc @exactlyallan

**Comment by bryevdv** [comment]
cc @AjayThorve Here is the process that a user contributed for running Bokeh server apps on JupyterHub behind a proxy:

http://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html#jupyterhub

I thought there was an extension someone created as well that might simplify this,  but I have not been able to find it yet.

**Comment by AjayThorve** [comment]
fix in progress, should be up in sometime today

**Comment by AjayThorve** [comment]
this should be fixed with a patch to cuxfilter (now release on rapidsai-nightly conda channel), and a minor update to the notebook in #24. 

the change is instead of `d.show()`, we now need - 

![image](https://user-images.githubusercontent.com/20476096/94978079-8ec64800-04d0-11eb-9700-5102d0a95382.png)

where `notebook_url` parameter needs to be updated and replaced with current binder base_url, like `https://hub-binder.mybinder.ovh`, this could be a static update if the baes_url of the course binder is going to be stable, but if its user-specifc, the user would have to update it themselves.

cc @exactlyallan @bryevdv @jtpio

**Comment by jtpio** [comment]
Thanks @AjayThorve.

Yes the setup is similar to https://mybinder.org, and will include the username in the url (`/user/foobar`).

Have you been able to try that `cuxfilter` works on https://mybinder.org? If it works there then it should also work here after changing the base URL.

**Comment by AjayThorve** [comment]
Hi @jtpio , I could not test it on mybinder.org, as I did not have access to a gpu based environment to run cuxfilter, although I did manage to run a local instance internally for jupyterhub (with https), and that seemed to work fine.

**Comment by jtpio** [comment]
ok I thought it would be possible to test the app part of the cuxfilter dashboard only without GPU.

To make sure it is served properly.
